# Using ChatGPT

There are now many AI-based tools to help us code. These tools can create code outlines for us, check our own code, write functions, and explain the steps. I'm going to show you a few examples using the free [OpenAI ChapGPT tools](https://chat.openai.com).

If you use Github and VS Code, you can sign-up for [CoPilot](https://github.com/features/copilot/). 

This paper by [Liu, Miller, and Niu (2023)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4412371) has some great examples of how to use ChatGPT in a course like this one.

```{note}
There's a trade-off when using AI code assists. They will make you faster and check your syntax. They work well for simple tasks in a introductory course like this. But, at some point, you want to understand the code. You'll need to tweak it to get it to work. And, if you're doing more interesting coding, they may be of limited use. So - use them, but with these caveats in mind!
```

## Using GPT to Write a Function For You

Let's go to Chapter 7, where I show you how to write a function to generate asset paths using **geometric brownian motion**. We use the Nasdaq API to bring in some bitcoin data in that example. Now, I'm going to use ChatGPT to write the same function. I gave GPT4 the following prompt:

> Write a function in Python that simulates geometric brownian motion for any number of assets. Create the appropriate inputs as arrays. The inputs should be the number of assets, the mean for each asset, the standard deviation for each asset, the number of periods, the initial value of each asset, and the number of simulations. The output should be an array that contains all of the simulations for each asset. These are uncorrelated assets, so don't worry about covariance.

Here's the code that it gave me:

In [1]:
import numpy as np

def geometric_brownian_motion(num_assets, means, std_devs, num_periods, initial_values, num_simulations):
    if len(means) != num_assets or len(std_devs) != num_assets or len(initial_values) != num_assets:
        raise ValueError("The length of means, std_devs, and initial_values should be equal to the number of assets")

    # Initialize an array to store the simulations
    simulations = np.zeros((num_simulations, num_periods + 1, num_assets))

    # Set the initial values for each simulation
    simulations[:, 0, :] = initial_values

    # Time step
    dt = 1.0

    # Loop through each simulation
    for sim in range(num_simulations):
        # Loop through each time period
        for t in range(1, num_periods + 1):
            # Loop through each asset
            for asset in range(num_assets):
                # Generate a random normal value (using mean=0 and std_dev=1) for the brownian motion
                random_normal = np.random.normal(0, 1)

                # Calculate the change in asset value using geometric brownian motion
                change = means[asset] * dt + std_devs[asset] * np.sqrt(dt) * random_normal

                # Update the asset value
                simulations[sim, t, asset] = simulations[sim, t - 1, asset] * np.exp(change)

    return simulations

# Example usage
num_assets = 3
means = np.array([0.05, 0.06, 0.07])
std_devs = np.array([0.1, 0.12, 0.14])
num_periods = 100
initial_values = np.array([100, 120, 140])
num_simulations = 1000

simulations = geometric_brownian_motion(num_assets, means, std_devs, num_periods, initial_values, num_simulations)
print(simulations)

[[[1.00000000e+02 1.20000000e+02 1.40000000e+02]
  [1.01454695e+02 1.28069966e+02 1.70652407e+02]
  [1.12871751e+02 1.41467282e+02 1.49600433e+02]
  ...
  [5.02178038e+03 9.71524115e+04 4.35792597e+04]
  [5.55015488e+03 1.07377625e+05 4.80448017e+04]
  [5.52979220e+03 1.16761678e+05 5.31366182e+04]]

 [[1.00000000e+02 1.20000000e+02 1.40000000e+02]
  [1.18459685e+02 1.30576373e+02 1.65925942e+02]
  [1.15188946e+02 1.45705186e+02 1.45249885e+02]
  ...
  [2.06505980e+03 6.35635631e+04 2.74755637e+05]
  [1.97285849e+03 6.40277723e+04 2.64094630e+05]
  [1.77567309e+03 7.17466401e+04 2.69337369e+05]]

 [[1.00000000e+02 1.20000000e+02 1.40000000e+02]
  [8.85625216e+01 1.17885285e+02 1.37441509e+02]
  [9.22855897e+01 1.29286949e+02 1.52438399e+02]
  ...
  [3.26623556e+04 6.81011625e+04 2.24659060e+04]
  [3.12811369e+04 6.84016758e+04 2.48920434e+04]
  [3.22638415e+04 8.66167055e+04 3.18463627e+04]]

 ...

 [[1.00000000e+02 1.20000000e+02 1.40000000e+02]
  [1.13399293e+02 1.16274380e+02 1.6294

Here's the GPT explanation of the code.

> This function accepts the following inputs:

> num_assets: the number of assets \
means: a NumPy array containing the mean return for each asset \
std_devs: a NumPy array containing the standard deviation of return for each asset \
num_periods: the number of time periods \
initial_values: a NumPy array containing the initial value for each asset \
num_simulations: the number of simulations to run

> The function returns a 3D NumPy array containing the simulations for each asset, with dimensions (num_simulations, num_periods + 1, num_assets).

Let's look a bit more at the output. I'll get its `.shape` attribute.

In [2]:
type(simulations)

numpy.ndarray

In [3]:
simulations.shape

(1000, 101, 3)

The output is a **three-dimensional array**. We can pull out all of the simulations for one asset, as well as a single simulation for one asset. Or anything else.

In [4]:
# All simulations for the first asset.
simulations[:,:,0]

array([[  100.        ,   101.45469512,   112.87175115, ...,
         5021.78038189,  5550.15488485,  5529.79220422],
       [  100.        ,   118.45968483,   115.18894554, ...,
         2065.05980266,  1972.85849015,  1775.67309449],
       [  100.        ,    88.56252163,    92.28558966, ...,
        32662.35563748, 31281.13690003, 32263.84148293],
       ...,
       [  100.        ,   113.39929347,   123.3986092 , ...,
         3568.47250761,  3710.85018163,  4300.9611138 ],
       [  100.        ,   104.51886134,   104.97159651, ...,
         6930.0582691 ,  6991.59476763,  7883.10626147],
       [  100.        ,    98.12581204,    99.26322622, ...,
        15020.53302051, 14156.02736419, 15654.66180678]])

In [5]:
# All simulations for the second asset.
simulations[:,:,1]

array([[1.20000000e+02, 1.28069966e+02, 1.41467282e+02, ...,
        9.71524115e+04, 1.07377625e+05, 1.16761678e+05],
       [1.20000000e+02, 1.30576373e+02, 1.45705186e+02, ...,
        6.35635631e+04, 6.40277723e+04, 7.17466401e+04],
       [1.20000000e+02, 1.17885285e+02, 1.29286949e+02, ...,
        6.81011625e+04, 6.84016758e+04, 8.66167055e+04],
       ...,
       [1.20000000e+02, 1.16274380e+02, 1.19487008e+02, ...,
        1.22547705e+05, 1.67203855e+05, 1.83863414e+05],
       [1.20000000e+02, 1.12716702e+02, 9.78443362e+01, ...,
        5.92227707e+03, 6.71489641e+03, 8.70080703e+03],
       [1.20000000e+02, 1.37684271e+02, 2.02608548e+02, ...,
        2.30608331e+05, 2.47624959e+05, 2.96642671e+05]])

In [6]:
# First simulation for the first asset

simulations[0,:,0]

array([ 100.        ,  101.45469512,  112.87175115,  115.88885985,
        120.0567927 ,  112.49537473,  104.25037691,  129.38065427,
        126.5525271 ,  130.5138876 ,  144.10600377,  131.95939293,
        137.95281161,  172.59777983,  209.28086552,  232.25131834,
        189.38156934,  203.21910519,  194.89455332,  187.42667811,
        184.39888804,  189.84529573,  196.29891584,  206.45388647,
        211.04689031,  206.12371054,  194.36631956,  242.33693831,
        301.941213  ,  332.68135101,  321.63373941,  348.20228862,
        384.87054954,  398.01438566,  416.90996988,  458.05280024,
        438.35063458,  427.98939429,  427.4738059 ,  495.91705435,
        636.73603476,  710.14937564,  671.58127855,  865.76379214,
        914.53140254,  849.17705697, 1045.01981803,  982.19371801,
       1042.81510967,  924.46325685, 1016.04202755,  942.87105341,
        968.78168028,  944.21063526, 1141.58355201, 1234.36884058,
       1324.66403048, 1313.28718413, 1314.99247433, 1289.99909

Compare this code to the one we used above. What's different? What stands out to you? What assumptions did it make? What's up with these numbers?

GPT is quite good at creating code that has been done in a lot of places. It has trained on millions of online tutorials and examples. However, you still want to follow the logic and check for errors. **There will be errors.**

**You can have a "dialog" with GPT.** Look at the code. Is it what you want? You can ask it to change it for you.

**What does that leave for us to do?** Use GPT to start sketching your code. Figure out the questions that you're trying answer. What's the problem that you're trying to solve? Who are you solving it for? What will the answer look like? What will it tell you?

Using tools like GPT, Github Co-Pilot, etc. is like having a team of junior programmers working for you. They can make the job easier, but it is still up to you to know what's an interesting question in the first place. **You still need to use your domain expertise and creativity to come up with solutions to problems that aren't in an online Python tutorials.**

## Using ChatGPT to Check Our Code

Below, I have borrowed some code from our portfolio optimization code. However, there is one small problem, based on one I encountered in class. One of those small, tiny errors that can be so frustrating! Do you see it?

In [7]:
# Read in some eod prices
import numpy as np
import pandas as pd

from pylab import mpl, plt

import scipy.optimize as sco

raw = pd.read_csv('https://raw.githubusercontent.com/aaiken1/fin-data-analysis-python/main/data/tr_eikon_eod_data.csv',
                  index_col=0, parse_dates=True).dropna() 

symbols = ['AAPL.O', 'MSFT.O', 'SPY', 'GLD'] #two stocks and two ETFs

noa = len(symbols) #noa = number of assets

data = raw[symbols]

rets = data.pct_change().dropna()

noa = 4

weights = np.random.random(noa)
weights /= np.sum(weights)

ann_rets = rets.mean() * 252

def port_ret(weights):
    return np.sum(ann_rets * weights)

def port_vol(weights):
    return np.sort(np.dot(weights.T, np.dot(rets.cov() * 252, weights)))

def sharpe(weights):  
    return port_ret(weights) / port_vol(weights)  

sharpe(weights)


AxisError: axis -1 is out of bounds for array of dimension 0

Huh... Let's see if ChatGPT can help us out. I'm going to copy and paste the code and ask it to find the mistake. It does!

```{figure} ../images/17-gpt-find-error.png
---
name: 17-gpt-find-error.png
align: center
class: with-border
---
You can use ChatGPT to find errors in your code.
```